config/routes.rb
CraigslistJr::Application.routes.draw do

  root :to => 'categories#index'

  resources :categories
  resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  
  has_many :posts
  validates :title, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :key, :category_id

  belongs_to :category

  validates :title, :presence => true
  validates :body, :presence => true
  before_save :generate_key

  def generate_key
    self.key = SecureRandom.random_number(1000000)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

# attr_reader :new 

def index
  @categories = Category.all
end

def show
  @category = Category.find(params[:id])
end

def new
  @category = Category.new
end

def create
  @category = Category.new(params[:category])
    if @category.save
      render :show

      # render category_path(@category.id)
    else
      render :new
    end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    p params
    @post = Post.new
  end

  def create
    p params
    @post = Post.new(params[:post])
    if @post.save
      render :show_key
    else
      render :new
    end
  end

  def edit
    p params
     @post = Post.find(params[:id])
     if @post.key == params[:key]
      render :edit
    else
      @error = "Your key was not found in the database."
      render :show
    end 
  end

  def update
    p params
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      render :show_key
    else
      render :edit
    end  
  end

end

app/controllers/posts_controller_old.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to "New Category", new_category_path %>
<ul>
<% @categories.each do |category| %>
<li><%= link_to category.title, category_path(category) %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>  
  <%= f.text_field :title %>
  <%= f.submit "Create" %>
<% end %>

app/views/categories/show.html.erb
Category: <%= @category.title %></br></br>
<%= link_to "New Post", new_post_path(@category) %>

<% @category.posts.each do |post| %>
  <ul class="post">
  <li><%= link_to post.title, post_path(post) %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
<%= f.hidden_field  :category_id, :value => @post.category_id %>
<%= f.text_field :title, :value => @post.title %>
<%= f.text_area :body, :value => @post.body %>
<%= f.submit "Submit" %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= f.hidden_field  :category_id, :value => params[:format] %>
<%= f.text_field :title %>
<%= f.text_area :body %>
<%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<h2>Post</h2>

<% if @error %>
<p><%= @error %></p>
<% end %>

Title: <%= @post.title %></br></br>
Content: <%= @post.body %>

app/views/posts/show_key.html.erb
<h2>Post</h2>

Edit URL: <%= link_to edit_post_url(@post) + '?key=' + @post.key.to_s, edit_post_url(@post) + '?key=' + @post.key.to_s %><br><br>

Title: <%= @post.title %></br></br>
Content: <%= @post.body %>

app/views/posts/update.html.erb
<h2>Post</h2>


Title: <%= @post.title %></br></br>
Content: <%= @post.body %>